export const ALPHABET_DATA = [
  { letter: 'A', animal: 'Abelha', emoji: '🐝', color: 'bg-yellow-100' },
  { letter: 'B', animal: 'Baleia', emoji: '🐋', color: 'bg-blue-100' },
  { letter: 'C', animal: 'Cachorro', emoji: '🐶', color: 'bg-orange-100' },
  { letter: 'D', animal: 'Dinossauro', emoji: '🦖', color: 'bg-green-100' },
  { letter: 'E', animal: 'Elefante', emoji: '🐘', color: 'bg-indigo-100' },
  { letter: 'F', animal: 'Foca', emoji: '🦭', color: 'bg-cyan-100' },
  { letter: 'G', animal: 'Gato', emoji: '🐱', color: 'bg-amber-100' },
  { letter: 'H', animal: 'Hipopótamo', emoji: '🦛', color: 'bg-slate-100' },
  { letter: 'I', animal: 'Iguana', emoji: '🦎', color: 'bg-emerald-100' },
  { letter: 'J', animal: 'Jacaré', emoji: '🐊', color: 'bg-green-200' },
  { letter: 'L', animal: 'Leão', emoji: '🦁', color: 'bg-orange-200' },
  { letter: 'M', animal: 'Macaco', emoji: '🐒', color: 'bg-amber-200' },
  { letter: 'N', animal: 'Naja', emoji: '🐍', color: 'bg-lime-100' },
  { letter: 'O', animal: 'Ovelha', emoji: '🐑', color: 'bg-stone-100' },
  { letter: 'P', animal: 'Pato', emoji: '🦆', color: 'bg-yellow-200' },
  { letter: 'Q', animal: 'Quati', emoji: '🦝', color: 'bg-gray-200' },
  { letter: 'R', animal: 'Rato', emoji: '🐭', color: 'bg-zinc-100' },
  { letter: 'S', animal: 'Sapo', emoji: '🐸', color: 'bg-green-300' },
  { letter: 'T', animal: 'Tigre', emoji: '🐯', color: 'bg-orange-300' },
  { letter: 'U', animal: 'Urso', emoji: '🐻', color: 'bg-stone-200' },
  { letter: 'V', animal: 'Vaca', emoji: '🐮', color: 'bg-red-50' },
  { letter: 'Z', animal: 'Zebra', emoji: '🦓', color: 'bg-slate-200' },
];

export const ANIMALS = [
  { name: 'Leão', emoji: '🦁', color: 'bg-orange-100', sound: 'O leão faz: rrrrroooar!' },
  { name: 'Elefante', emoji: '🐘', color: 'bg-blue-100', sound: 'O elefante faz: fuuuuuuu!' },
  { name: 'Macaco', emoji: '🐒', color: 'bg-amber-100', sound: 'O macaco faz: u-u-a-a!' },
  { name: 'Girafa', emoji: '🦒', color: 'bg-yellow-100', sound: 'A girafa é muito alta e silenciosa!' },
  { name: 'Zebra', emoji: '🦓', color: 'bg-stone-100', sound: 'A zebra galopa no campo!' },
  { name: 'Panda', emoji: '🐼', color: 'bg-slate-100', sound: 'O panda adora comer bambu!' },
  { name: 'Tigre', emoji: '🐯', color: 'bg-orange-200', sound: 'O tigre é um gato listrado gigante!' },
  { name: 'Coelho', emoji: '🐰', color: 'bg-pink-100', sound: 'O coelho pula bem alto!' },
  { name: 'Porco', emoji: '🐷', color: 'bg-pink-200', sound: 'O porco faz: oinc oinc!' },
  { name: 'Pinto', emoji: '🐥', color: 'bg-yellow-200', sound: 'O pintinho faz: piu piu!' },
  { name: 'Vaca', emoji: '🐮', color: 'bg-red-50', sound: 'A vaca faz: muuuuu!' },
  { name: 'Sapo', emoji: '🐸', color: 'bg-green-100', sound: 'O sapo faz: ribit ribit!' },
  { name: 'Baleia', emoji: '🐋', color: 'bg-blue-200', sound: 'A baleia canta no fundo do mar!' },
  { name: 'Pinguim', emoji: '🐧', color: 'bg-cyan-50', sound: 'O pinguim anda balançando!' },
  { name: 'Tartaruga', emoji: '🐢', color: 'bg-emerald-200', sound: 'A tartaruga anda bem devagar!' },
  { name: 'Polvo', emoji: '🐙', color: 'bg-purple-200', sound: 'O polvo tem oito braços!' },
  { name: 'Caranguejo', emoji: '🦀', color: 'bg-red-100', sound: 'O caranguejo anda de ladinho!' },
  { name: 'Borboleta', emoji: '🦋', color: 'bg-pink-50', sound: 'A borboleta voa entre as flores!' },
  { name: 'Abelha', emoji: '🐝', color: 'bg-yellow-300', sound: 'A abelha faz: bzzzzzz!' },
  { name: 'Coruja', emoji: '🦉', color: 'bg-brown-100', sound: 'A coruja faz: uuuuu uuuuu!' },
  { name: 'Morcego', emoji: '🦇', color: 'bg-gray-300', sound: 'O morcego voa na noite!' },
  { name: 'Esquilo', emoji: '🐿️', color: 'bg-orange-50', sound: 'O esquilo adora nozes!' },
  { name: 'Canguru', emoji: '🦘', color: 'bg-amber-50', sound: 'O canguru pula muito longe!' },
  { name: 'Hipopótamo', emoji: '🦛', color: 'bg-indigo-50', sound: 'O hipopótamo adora água!' },
  { name: 'Tubarão', emoji: '🦈', color: 'bg-blue-300', sound: 'O tubarão nada rápido no oceano!' },
  { name: 'Galinha', emoji: '🐔', color: 'bg-orange-50', sound: 'A galinha faz: có-có-ri-có!' },
  { name: 'Cavalo', emoji: '🐎', color: 'bg-amber-200', sound: 'O cavalo faz: i-hó-hó!' },
  { name: 'Ovelha', emoji: '🐑', color: 'bg-stone-50', sound: 'A ovelha faz: méééé!' },
  { name: 'Pato', emoji: '🦆', color: 'bg-yellow-100', sound: 'O pato faz: quack quack!' },
  { name: 'Jacaré', emoji: '🐊', color: 'bg-green-400', sound: 'O jacaré abre o bocão!' },
  { name: 'Rato', emoji: '🐭', color: 'bg-zinc-200', sound: 'O rato faz: squeak squeak!' },
  { name: 'Formiga', emoji: '🐜', color: 'bg-red-50', sound: 'A formiga carrega folhinhas!' },
  { name: 'Aranha', emoji: '🕷️', color: 'bg-slate-300', sound: 'A aranha tece sua teia!' },
  { name: 'Caracol', emoji: '🐌', color: 'bg-lime-50', sound: 'O caracol leva sua casinha nas costas!' },
];

export const ROUNDS_PER_GAME = 5;

export const COLORS_DATA = [
  { name: 'Vermelho', color: 'bg-red-500', emoji: '🍎', object: 'Maçã' },
  { name: 'Azul', color: 'bg-blue-500', emoji: '🦋', object: 'Borboleta' },
  { name: 'Amarelo', color: 'bg-yellow-400', emoji: '☀️', object: 'Sol' },
  { name: 'Verde', color: 'bg-green-500', emoji: '🌳', object: 'Árvore' },
  { name: 'Laranja', color: 'bg-orange-500', emoji: '🍊', object: 'Laranja' },
  { name: 'Roxo', color: 'bg-purple-500', emoji: '🍇', object: 'Uva' },
  { name: 'Rosa', color: 'bg-pink-400', emoji: '🌸', object: 'Flor' },
];
